### ISSUE TITLE
gradle, ant, or maven build needed for this code

### ISSUE THREAD

**Issue by eric-jahn** [PCNI/OpenHMIS#1]
That way, all the dependencies will be accounted for, and will automate the installation.

**Comment by WilliamMatson** [comment]
Unless we want to revisit the entire process, we decided that we would not implement Maven due to its complexity.

-----Original Message-----

**Comment by eric-jahn** [comment]
I think since we've had that discussion, Maven's only grown in popularity to the extent it's now the defacto build tool for Java.  Also, Eclipse has heavily embraced Maven since then, and it's included by default in Eclipse.  If it was ever complex, it's pretty much point and click and auto generating now.  Also, it does more than Ant, as it uses Ant.  So, yes, probably time to revisit...

**Comment by kfogel** [comment]
Just seconding what Eric says.  Pretty much every Java-based open source project uses _some_ build system, and Maven is one of the most popular such systems.  I'm not sure when the decision was made not to use it, but would recommend revisiting it now -- incoming developers would expect some build framework, and would consider Maven to be a very normal choice.  (As far as I know, Ant is fine too; I'm not enough of a Java developer myself to evaluate the pros and cons between them.  The main thing is to have some standard build system in place; which one it is is secondary.)

**Comment by imlab10** [comment]
That decision was made couple years back. Maven was not stable at that
time, specially for circular dependencies and online repositories issues.
Lots of projects went to maven at that time and eventually it was pulled
out. I think Beini also run into lots of issues when she took over some
projects from outside and eventually she pulled maven out in order not to
waste more time. If Maven is more mature, stable and easy to use, we can
certainly re-visit this topic.

**Comment by kfogel** [comment]
Again, want to emphasize that this isn't really about Maven vs not-Maven.  It's about having a build system in place -- could be Ant or, alternatively, could be whatever the cool kids are using these days (if that's not Maven).

Right now, starting from the top of the tree and the INSTALL.md file, there is not a clear path (e.g., a command to issue) to compile all the source code to get a runnable program.  That's the problem that needs solving -- Maven is just one of various possible solutions to that problem.

**Comment by ashaar364** [comment]
Ant build system is added and INSTALL.md file is updated about the configuration in the system.
You can use the following three command "ant deploy", "ant compile" and "ant clean". deploy is using the other two ant commands.
ant deploy will create the war file and copied to the Tomcat webApp directory. Ant can be configured with any other app or web application server.

**Comment by steveconners** [comment]
I'm going to fill out the choir saying there needs to be a standard way that eases the on-ramp for new contributors.

Ashaar - the current master branch does not include Ant builds. I see them in the OAuth branch, however, I encounter errors attempting an Ant deploy on the CentOS VM that Xin put together. I will do a little more exploration.

I do not think a glitzy build is going to be what convinces people to contribute or not. I will push toward a standardized development VM with a reliable build straight out of GitHub. Today, that looks like it will be (CentOS - MySQL - MySQL Workbench - Eclipse - Tomcat - JDK - Ant) running on VirtualBox. I have successfully Git'd, built, and used some portions of our architecture on this platform. We have Maven managing the builds for some code, however, it has not been used reliably.

My current goal will be to build a stable develop-build-test environment that can be used by collaborators. Honestly, I think the folks reading this are not the target audience, as you are the people that can tweak your development environment as required, however if you have any comments, concerns, or requests, please let me know.

Once we have a stable architecture for  this work, we can look at forking to support both Ant and Maven, or both CentOS and Debian. There are components of our architecture for which we need to support Jetty, however we will consolidate to Tomcat first, then consider supporting both for ALL of our components, rather than some selectively support based on component.

**Comment by slifty** [comment]
Hey all -- I just put out a pull request which builds using maven, so if that gets merged in we should be able to mark this issue as closed!
