### ISSUE TITLE
Oauth2 Authentication 

### ISSUE THREAD

**Issue by slifty** [PCNI/OpenHMIS#21]
The API currently does not have any form of enabled authentication -- this was a temporary measure which should be immediately corrected by the guy who ruined it (that would be me).

My understanding is that we would like to use [oauth2](http://oauth.net/2/) focusing on SalesForce and (or?) Google, but I'm also going to spend some time making sure I understand the use cases for authentication to ensure that these two providers cover our needs.

**Comment by kfogel** [comment]
I believe those two are correct, but check on list & with Dave.

**Comment by steveconners** [comment]
The initial implementation was Google and Salesforce, Ashaar is currently adding a custom OpenHMIS oauth2 server.

**Comment by kfogel** [comment]
As far as I can tell, this issue is done.  Google Sign-In works, and other authn providers can be added as needed.  It doesn't seem like a good idea to leave the issue open just for Salesforce, because that's just one of N authn providers that will probably need to be implemented in the long run.  We can open a dedicated ticket for Salesforce if/when that becomes a hard requirement.

Closing, but please re-open if I misunderstood anything.
